document.writeln("<div class=\"footer_nav\">");
document.writeln("<div class=\"footer_box\">");
document.writeln("<h3>Stone Crusher</h3>");
document.writeln("<ul>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/py-cone-crusher.html\">PY Cone Crusher</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/pf-impact-crusher.html\">PF Impact Crusher</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/vsi5x-crusher.html\">VSI5X Crusher</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/hst-cone-crusher.html\">HST Cone Crusher</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/pfw-impact-crusher.html\">PFW Impact Crusher</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/vsi-crusher.html\">VSI Crusher</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/pew-jaw-crusher.html\">PEW Jaw Crusher</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div class=\"footer_box\">");
document.writeln("<h3>Grinding Mills</h3>");
document.writeln("<ul>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/mtm-trapezium-grinder.html\">MTM Trapezium Grinder</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/scm-ultrafine-mill.html\">SCM Ultrafine Mill</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/lm-vertical-grinding-mill.html\">LM Vertical Grinding Mill</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/mtw-milling-machine.html\">MTW Milling Machine</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/lum-ultrafine-vertical-roller-mill.html\">LUM Ultrafine Vertical Roller Mill</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/raymond-mill.html\">Raymond Mill</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/products/ball-mill.html\">Ball Mill</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div class=\"footer_box\">");
document.writeln("<h3>Hot Solutions</h3>");
document.writeln("<ul>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/sand-making-plant.html\">Sand Making Plant</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/iron-ore-beneficiation-plant.html\">Iron ore beneficiation plant</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/limestone-crushing-plant.html\">Limestone crushing plant</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/copper-ore-beneficiation-plant.html\">Copper ore beneficiation plant</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/talc-processing-plant.html\">Talc processing plant</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/clay-processing-plant.html\">Clay processing plant</a></li>");
document.writeln("<li><a rel=\"nofollow\" href=\"/solutions/river-stone-processing-plant.html\">River stone processing plant</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div class=\"footer_box\">");
document.writeln("<h3>Contact Us</h3>");
document.writeln("<ul>");
document.writeln("<li>Office Add: No.416 Jianye Road, South Jinqiao Area,Pudong New Area, Shanghai, China.</li>");
document.writeln("<li>Whatsapp: <a href="https://whatsapp.shibangsoft.com/WhatsApp.php">+86-13621919955</a></li>");
document.writeln("");
document.writeln("<li>Postcode: 201201</li>");
document.writeln("<li>E-mail: sale@shibang-china.com</li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");